name: Create Release Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v0.1.0)

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checksumdir

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Update version in files
        run: |
          # Update shell scripts
          sed -i "s/Version: [0-9]\+\.[0-9]\+\.[0-9]\+/Version: ${{ steps.version.outputs.version }}/g" scripts/*.sh
          
          # Update PowerShell scripts
          sed -i "s/\$SCRIPT_VERSION = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\$SCRIPT_VERSION = \"${{ steps.version.outputs.version }}\"/g" scripts/*.ps1
          
          # Update README.md if it contains version information
          sed -i "s/Version: [0-9]\+\.[0-9]\+\.[0-9]\+/Version: ${{ steps.version.outputs.version }}/g" README.md

      - name: Create package directory
        run: |
          mkdir -p universal-installer
          cp -r scripts universal-installer/
          cp README.md universal-installer/
          cp LICENSE universal-installer/
          cp version.txt universal-installer/

      - name: Create zip file
        run: |
          zip -r universal-installer.zip universal-installer/

      - name: Generate checksum
        run: |
          sha256sum universal-installer.zip > universal-installer.zip.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: |
            universal-installer.zip
            universal-installer.zip.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 